<a href="https://colab.research.google.com/github/WILLIAMTBOY/Pandax/blob/main/ASSIGNMENT_StandardScaler().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [5]:
Dataset1 = pd.read_csv("/content/heart.csv")
Dataset1

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [7]:
Dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [9]:
Dataset1.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [10]:
Dataset1.shape

(1025, 14)

In [12]:
X = Dataset1.drop(columns = 'target')
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   0     3  
2         0   0     3  
3         2   1     3  
4         1   3     2  
...     ...  ..   ...  
1020      2   0     2  
1021      1   1     3  
1022      1   1     2  
1023      2   0     2  
1024      1   1     3  

[1025 rows x 13 columns]

In [13]:
Y = Dataset1[['target']]
Y

target
0          0
1          0
2          0
3          0
4          0
...      ...
1020       1
1021       0
1022       0
1023       1
1024       0

[1025 rows x 1 columns]

In [14]:
# Train Test Split

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, train_size = 0.75, random_state = 42)

In [17]:
print(X_train.shape)

(768, 13)


In [18]:
print(X_test.shape)

(257, 13)


In [19]:
print(Y_train.shape)

(768, 1)


In [20]:
print(Y_test.shape)

(257, 1)


In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
model1 = LinearRegression()

In [23]:
model1.fit(X_train, Y_train)

LinearRegression()

In [24]:
Y_pred = model1.predict(X_test)

In [25]:
print(Y_pred.shape)

(257, 1)


In [26]:
from sklearn.metrics import r2_score

In [28]:
print(r2_score(Y_test,Y_pred))

0.415052272467062


In [29]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
527   62    0   0       124   209    0        1      163      0      0.0   
359   53    0   2       128   216    0        0      115      0      0.0   
447   55    1   0       160   289    0        0      145      1      0.8   
31    50    0   1       120   244    0        1      162      0      1.1   
621   48    1   0       130   256    1        0      150      1      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
940   57    0   0       140   241    0        1      123      1      0.2   
787   51    1   0       140   298    0        1      122      1      4.2   
926   54    1   0       110   206    0        0      108      1      0.0   
249   42    1   2       130   180    0        1      150      0      0.0   
552   43    0   0       132   341    1        0      136      1      3.0   

     slope  ca  thal  
527      2   0     2  
359      2   0     0  
447      1   1     3  
31       2   0     2  
621      2   2     3  
..     ...  ..   ...  
940      1   0     3  
787      1   3     3  
926      1   1     2  
249      2   0     2  
552      1   0     3  

[257 rows x 13 columns]

In [30]:
Y_test

target
527       1
359       1
447       0
31        1
621       0
..      ...
940       0
787       0
926       0
249       1
552       0

[257 rows x 1 columns]

In [31]:
Y_pred

array([[ 0.9439327 ],
       [ 1.27741444],
       [ 0.03702861],
       [ 0.9410318 ],
       [ 0.18132433],
       [ 0.62611243],
       [-0.05667887],
       [-0.13230254],
       [ 0.75819267],
       [-0.0109036 ],
       [ 0.99002253],
       [-0.22298477],
       [ 0.77624361],
       [ 0.76228497],
       [ 0.24412137],
       [ 0.86250478],
       [-0.09520748],
       [ 0.96717301],
       [ 0.69750249],
       [-0.03403763],
       [ 0.72966213],
       [ 0.16198362],
       [ 0.53487129],
       [-0.18071591],
       [ 0.72966213],
       [ 0.6238848 ],
       [ 1.0061906 ],
       [ 0.55941573],
       [-0.15253215],
       [ 0.82366555],
       [ 0.64394615],
       [ 0.75344058],
       [ 0.487744  ],
       [ 1.27741444],
       [ 0.74887915],
       [ 0.66764632],
       [ 0.72966213],
       [ 0.4900882 ],
       [ 0.69439361],
       [ 0.87007186],
       [-0.13230254],
       [ 0.17944757],
       [ 0.52714603],
       [ 0.53487129],
       [ 0.31949291],
       [-0

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
scaler = StandardScaler()

In [35]:
print(scaler.fit(Dataset1))

StandardScaler()


In [48]:
scaled_data = scaler.fit_transform(Dataset1)

In [49]:
print(scaler.mean_)

[5.44341463e+01 6.95609756e-01 9.42439024e-01 1.31611707e+02
 2.46000000e+02 1.49268293e-01 5.29756098e-01 1.49114146e+02
 3.36585366e-01 1.07151220e+00 1.38536585e+00 7.54146341e-01
 2.32390244e+00 5.13170732e-01]


In [50]:
print(scaler.transform(Dataset1))

[[-0.26843658  0.66150409 -0.91575542 ...  1.20922066  1.08985168
  -1.02669772]
 [-0.15815703  0.66150409 -0.91575542 ... -0.73197147  1.08985168
  -1.02669772]
 [ 1.71659547  0.66150409 -0.91575542 ... -0.73197147  1.08985168
  -1.02669772]
 ...
 [-0.81983438  0.66150409 -0.91575542 ...  0.23862459 -0.52212231
  -1.02669772]
 [-0.4889957  -1.51170646 -0.91575542 ... -0.73197147 -0.52212231
   0.97399651]
 [-0.04787747  0.66150409 -0.91575542 ...  0.23862459  1.08985168
  -1.02669772]]


In [51]:
print(Dataset1)

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0

In [54]:
scaled_data.mean(axis = 0)

array([-3.43140150e-16,  1.80235231e-16,  5.54569940e-17, -7.03610612e-16,
       -3.46606213e-18, -4.15927455e-17, -8.31854910e-17, -4.33257766e-16,
       -7.62533668e-17, -2.42624349e-16,  1.85434324e-16,  1.81968262e-17,
        2.53022535e-16,  3.81266834e-17])

In [56]:
scaled_data.std(axis = 0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])